grails-app/domain/triage/Paciente.groovy
/* 
Copyright (C) 2015  Nestor Muñoz. nestorgabriel2008@gmail.com; Marcia Tejeda. tejedamarcia@gmail.com

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/

package triage

class Paciente {

	Date fechaHoraIngreso = new Date()
	Date fechaHoraAtencion

	String sistole
	String diastole
	String pulso
	String frecuenciaRespiratoria
	String temperatura
	String saturacionO2
	String glucosa
	Boolean finalizado = false
	Integer tipoAtencion


	Prioridad prioridad

	static belongsTo = [persona : Persona]
	static hasMany = [sintomas : Sintoma]

	static constraints = {
		fechaHoraAtencion nullable: true
		sistole nullable: true
		diastole nullable: true
		pulso nullable: true
		frecuenciaRespiratoria nullable: true
		temperatura nullable: true
		saturacionO2 nullable: true
		glucosa nullable: true
		sintomas nullable: true
		prioridad nullable: true
		tipoAtencion nullable: true
	}

	/**
	 * Obtiene la prioridad del paciente a partir de sus sintomas.
	 * En caso de que ya se haya calculado la prioridad, no volvemos a calcular
	 * @return Prioridad.DOS o Prioridad.TRES
	 */
	Prioridad calcularPrioridad(){
		Boolean esAdulto = persona.esAdulto()

		//CHEQUEO SI ES PRIORIDAD 1, lo normal seria que la prioridad uno se detecte sin llamar a este metodo pero igualmente se puede dar el caso en que se presione el boton "Fin triage" con sintomas de prioridad uno
		for(sintoma in sintomas){
			if((esAdulto && sintoma.prioridadAdulto == Prioridad.UNO) || (!esAdulto && sintoma.prioridadPediatrico == Prioridad.UNO)){
				this.prioridad = Prioridad.UNO
				this.save()
				return Prioridad.UNO
			}
		}

		//CHEQUEO SIGNOS VITALES PRIORIDAD UNO, ADULTO
		if(esAdulto && 
			(this.sistole == 'menos de 85' || this.sistole == 'más de 200'
			||
			this.diastole == 'menos de 50' || this.diastole == 'más de 110'
			||
			this.pulso == 'menos de 60' || this.pulso == 'más de 120'
			||
			this.saturacionO2 == 'menos de 95'
			||
			this.frecuenciaRespiratoria == 'menos de 12' || this.frecuenciaRespiratoria == 'más de 30'
			||
			this.temperatura == 'menos de 35' || this.temperatura == 'más de 41.0'
			||
			this.glucosa == 'menos de 50'
			)){

			this.prioridad = Prioridad.UNO
			this.save()
			return Prioridad.UNO
		}else{
			//CHEQUEO SIGNOS VITALES PRIORIDAD UNO, PEDIATRICOS MENORES DE UN ANIO
			if(this.esMenorDeUnAnio() && 
				(['menos de 60','121-130','131-140','141-150','151-165','más de 165'].contains(this.sistole)
				||
				['menos de 30','71-75', '76-80','81-85', '86-90', '91-95', '96-100','más de 100'].contains(this.diastole)
				||
				['menos de 50','50-60','61-70','71-80','más de 190'].contains(this.pulso)
				||
				this.saturacionO2 == 'menos de 95'
				||
				['menos de 10','10-15','más de 60'].contains(this.frecuenciaRespiratoria)
				||
				this.glucosa == 'menos de 50' || this.glucosa == 'más de 300'
				)){

				this.prioridad = Prioridad.UNO
				this.save()
				return Prioridad.UNO
			}else{
				//CHEQUEO SIGNOS VITALES PRIORIDAD UNO, PEDIATRICOS MENORES DE 6 ANIOS
				if(this.esMenorDe6Anios() && 
					([ 'menos de 60','60-70','151-165','más de 165'].contains(this.sistole)
					||
					['menos de 30','30-35','36-40','91-95','96-100','más de 100'].contains(this.diastole)
					||
					['menos de 50','50-60','171-180','181-190','más de 190'].contains(this.pulso)
					||
					this.saturacionO2 == 'menos de 95'
					||
					['menos de 10','51-55','56-60','más de 60'].contains(this.frecuenciaRespiratoria)
					||
					this.glucosa == 'menos de 50' || this.glucosa == 'más de 300'
					)){

					this.prioridad = Prioridad.UNO
					this.save()
					return Prioridad.UNO
				}else{
					//CHEQUEO SIGNOS VITALES PRIORIDAD UNO, PEDIATRICOS MAYORES DE 6 ANIOS
					if(!esAdulto && this.esMayorDe6Anios() && 
						(['menos de 60','60-70','71-84','más de 165'].contains(this.sistole)
						||
						['menos de 30','30-35','36-40','41-45','46-50','más de 100'].contains(this.diastole)
						||
						['menos de 50','161-170', '171-180','181-190', 'más de 190'].contains(this.pulso)
						||
						this.saturacionO2 == 'menos de 95'
						||
						['menos de 10','41-45','46-50','51-55','56-60','más de 60'].contains(this.frecuenciaRespiratoria)
						||
						this.glucosa == 'menos de 50' || this.glucosa == 'más de 300'
						)){

						this.prioridad = Prioridad.UNO
						this.save()
						return Prioridad.UNO
					}
				}
			}
		}

		//CHEQUEO SI ES PRIORIDAD 2
		for(sintoma in sintomas){
			if((esAdulto && sintoma.prioridadAdulto == Prioridad.DOS) || (!esAdulto && sintoma.prioridadPediatrico == Prioridad.DOS)){
				this.prioridad = Prioridad.DOS
				this.save()
				return Prioridad.DOS
			}
		}

		//me fijo si es prioridad 2 segun los signos vitales
		//NOTA: los unicos signos vitales que influyen en una hipotetica Prioridad 2 son la temperatura y la glucosa
		if((esAdulto && (['38.6-39.4', '39.5-41.0'].contains(this.temperatura) || this.glucosa == 'más de 300')) ||
		(this.esMenorDeTresMeses() && [
			'38.0-38.5',
			'38.6-39.4',
			'39.5-41.0',
			'más 41.0'
		].contains(this.temperatura)) ||
		(this.estaEntre3y36Meses() && ['39.5-41.0', 'más 41.0'].contains(this.temperatura))){
			this.prioridad = Prioridad.DOS
			this.save()
			return Prioridad.DOS
		}

		this.prioridad = Prioridad.TRES
		this.save()
		return Prioridad.TRES
	}

	/**
	 * Retorna el tiempo de espera entre el ingreso y la atencion
	 * @return String
	 */
	String demoraDeAtencion(){
		use(groovy.time.TimeCategory) {
			def duration = this.fechaHoraAtencion - this.fechaHoraIngreso

			return duration.days>0 ? duration.days + "dias": "" +
			duration.hours>0 ? duration.hours + "horas": "" +
			duration.minutes>0 ? duration.minutes + "minutos": ""
		}
	}


	/**
	 * Retorna el tiempo de espera del paciente desde que ingresó
	 * hasta ahora
	 * @return
	 */
	String tiempoEspera(){
		use(groovy.time.TimeCategory) {
			Date ahora = new Date()
			def duration = ahora - this.fechaHoraIngreso
			return 	duration
		}
	}

	/**
	 * Indica si el paciente es adulto (para marcar la diferencia entre Triage adulto o
	 * pediátrico)
	 * @return
	 */
	Boolean esAdulto(){
		return this.persona.esAdulto()
	}
	/**
	 * Indica si el paciente esmenor de tres meses
	 * @return
	 */
	Boolean esMenorDeTresMeses(){
		return this.persona.esMenorDeTresMeses()
	}

	/**
	 * Indica si el paciente tiene entre 3 y 36 meses
	 * @return
	 */
	Boolean estaEntre3y36Meses(){
		return this.persona.estaEntre3y36Meses()
	}

	Boolean esMayorDe6Anios(){
		return this.persona.esMayorDe6Anios()
	}

	Boolean esMenorDe6Anios(){
		return this.persona.esMenorDe6Anios()
	}

	Boolean esMenorDeUnAnio(){
		return this.persona.esMenorDeUnAnio()
	}

	String getStringTipoAtencion(){
		switch(this.tipoAtencion){
		 case 1:
		 	return "Ingresa"
		 case 2:
		 	return "Consultorio externo"
		 case 3:
		 	return "Retira sin atención"
		 default:
		    return ""
	    }
	}

	String getStringSintomas(){
		String resultado = ""
		for(sintoma in this.sintomas){
			resultado += sintoma.nombre +"; "
		}
		return resultado
	}

}

grails-app/controllers/triage/PacienteController.groovy
/* 
Copyright (C) 2015  Nestor Muñoz. nestorgabriel2008@gmail.com; Marcia Tejeda. tejedamarcia@gmail.com

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/

package triage


import static org.springframework.http.HttpStatus.*
import grails.converters.JSON
import grails.transaction.Transactional

import java.text.SimpleDateFormat
import java.util.Date;

import org.codehaus.groovy.grails.web.json.JSONObject
import org.hibernate.criterion.CriteriaSpecification
import org.hibernate.criterion.Projection

import java.lang.Exception

@Transactional //(readOnly = true)
class PacienteController extends LoginController{

	//esta variable restringe con que metodos HTTP pueden ser llamados los metodos de la clase.
	//Si no se especifica, los metodos de la clase pueden ser invocados por cualquier metodo HTTP
	static allowedMethods = [cargarPaciente: "POST"
		,cargarImpresionInicial: "POST"
		,cargarSintomasYResponder: "POST"
		,cargarSignosVitalesYResponder: "POST"
		,cargarSintomas: "POST"
		,getSignosVitales: "POST"
		,getSintomas: "POST"
		,finalizarTriage: "POST"
		,ajaxBuscarNoFinalizados: "POST"
		,finalizarPaciente: "POST"
		,cantidadDeConsultasSegunPrioridad: "POST"
		,cargarPacienteEnEspera: "POST"
		,tiempoEsperaSegunPrioridad: "POST"
		,traerDatosPaciente: "POST"
		,getRegistroDiario: "POST"]


	/**
	 * Método que devuelve la cantidad de consultas según prioridad 
	 * Se filtra por fechas desde y hasta, parámetros que se reciben por JSON
	 * @return
	 */
	def cantidadDeConsultasSegunPrioridad(){
		SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy")
		Date fechaDesde = sdf.parse(request.JSON.fechaDesde)
		Date fechaHasta = sdf.parse(request.JSON.fechaHasta)
		//Se agrega un día porque el date con horario cuenta sólo hasta las 00 hs..
		fechaHasta = agregarDias(fechaHasta, 1)
		SimpleDateFormat output = new SimpleDateFormat("yyyy-MM-dd")
		String formattedFechaDesde = output.format(fechaDesde)
		String formattedFechaHasta = output.format(fechaHasta)

		List prioridades = Paciente.executeQuery("select prioridad,count(*) as cantidad "+
				"FROM Paciente  "+
				" WHERE fecha_hora_ingreso between '" + formattedFechaDesde +
				"' and '" + formattedFechaHasta + "' and prioridad is not null group by prioridad order by cantidad")
		List resultado = new ArrayList()
		for (p in prioridades){
			resultado.add(new JSONObject('{"prioridad":' + p[0] +
					',"cantidad":"' + p[1] + '"}'))
		}

		render resultado as JSON
		return resultado
	}


	/**
	 * Consulta que retorna los tiempos de espera según prioridad
	 * en un determinado período de tiempo que viene por parámetro
	 * @return
	 */
	def tiempoEsperaSegunPrioridad(){
		SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy")
		Date fechaDesde = sdf.parse(request.JSON.fechaDesde)
		Date fechaHasta = sdf.parse(request.JSON.fechaHasta)
		//Se agrega un día porque el date con horario cuenta sólo hasta las 00 hs..
		fechaHasta = agregarDias(fechaHasta, 1)
		SimpleDateFormat output = new SimpleDateFormat("yyyy-MM-dd")
		String formattedFechaDesde = output.format(fechaDesde)
		String formattedFechaHasta = output.format(fechaHasta)


		List prioridades;
		try{			
			//POSTGRES
			prioridades = Paciente.executeQuery("SELECT  prioridad, "+
				"coalesce(((sum( (DATE_PART('day', fecha_hora_atencion - fecha_hora_ingreso) * 24 + "+
				   "DATE_PART('hour', fecha_hora_atencion - fecha_hora_ingreso)) * 60 + "+
                   "DATE_PART('minute', fecha_hora_atencion - fecha_hora_ingreso) ) ) )/count(*),0) as tiempo "+	
				"FROM Paciente	"+ 
				"WHERE fecha_hora_ingreso between '" + formattedFechaDesde +
				"' and '" + formattedFechaHasta + 
				"'and finalizado = true group by prioridad")
		}catch(Exception e){//si tira excepcion porque no conoce la funcion DATE_PART
			//H2
			prioridades = Paciente.executeQuery("SELECT  prioridad, "+
				"coalesce(((sum(datediff(ss, fecha_hora_ingreso, fecha_hora_atencion)) / 60) )/count(*),0) as tiempo "+	
				"FROM Paciente	"+ 
				"WHERE fecha_hora_ingreso between '" + formattedFechaDesde +
				"' and '" + formattedFechaHasta + 
				"'and finalizado = true group by prioridad")
		}
		
		List resultado = new ArrayList()
		for (p in prioridades){
			resultado.add(new JSONObject('{"prioridad":' + p[0] +
					',"tiempo":"' + p[1] + '"}'))
		}
		
		render resultado as JSON
		return resultado
	}


	/*
	 *Click boton Finalizar triage. Carga la impresion visual, los sintomas y los signos vitales
	 */
	@Transactional
	def finalizarTriage(){
		Paciente paciente = Paciente.get(request.JSON.id)
		request.JSON.sintomasImpresionVisual.each {
			paciente.addToSintomas(Sintoma.get(it.id))
		}
		this.cargarSintomas(paciente)
		this.cargarSignosVitales(paciente)
		request.JSON.prioridad = paciente.calcularPrioridad()
		this.enviarRespuesta(paciente)
	}


	/**
	 * Método que marca el paciente como finalizado.
	 * Levanta del JSON el id paciente y el tipo de finalización (ingresa, consultorio externo, se retira).
	 * @return
	 */
	@Transactional
	def finalizarPaciente(){
		Integer tipoFin = request.JSON.tipoFin
		Paciente paciente = Paciente.get(request.JSON.id)
		paciente.tipoAtencion = tipoFin
		paciente.finalizado = true
		paciente.fechaHoraAtencion = new Date();
		paciente.save(flush:true)
		render request.JSON
	}


	/**
	 * calcula la prioridad (DOS o TRES) y responde un JSON
	 */
	@Transactional
	def calcularPrioridad(){
		Paciente paciente = Paciente.get(request.JSON.id)
		paciente.calcularPrioridad()
		this.enviarRespuesta(paciente)
	}

	/**seleccion de paciente del listado de busqueda
	 * 
	 * @return el JSON del paciente
	 */
	@Transactional
	def cargarPaciente(){
		Persona persona = Persona.get(request.JSON.id)
		Paciente paciente = Paciente.withCriteria(uniqueResult: true) {//chequeo si el paciente ya esta cargado
			eq('finalizado', false)
			eq('persona', persona)
		}

		//esto hace lo mismo que withCriteria pero no es soportado por los test de Grails
		//Paciente paciente = Paciente.find("from Paciente where finalizado='FALSE' and persona=:persona", [persona: persona])

		//los test de Grails hacian una cosa rara, me devolvia un paciente con todo en null
		//entonces me vi obligado a agregar la condicion || paciente.id == null)
		if(paciente == null || paciente.id == null){//solo cargo el paciente si no esta cargado
			paciente = new Paciente(persona: persona).save( failOnError : true )
		}	

		request.JSON.id = paciente.id //piso el id de la persona con el id del paciente
		this.cargarPacienteEnEspera()
	}

	/**
	 * Carga un paciente que ya estaba en espera
	 * @return
	 */
	@Transactional
	def cargarPacienteEnEspera(){
		Paciente paciente = Paciente.get(request.JSON.id)
		request.JSON.id = paciente.id
		request.JSON.nombre = paciente.persona.nombre
		request.JSON.apellido = paciente.persona.apellido
		request.JSON.fechaDeNacimiento = paciente.persona.fechaDeNacimiento.getDateString()
		request.JSON.DNI = paciente.persona.dni
		request.JSON.esAdulto = paciente.esAdulto()
		if(!request.JSON.esAdulto){//es pediatrico
			request.JSON.categoriaPediatrico = paciente.persona.getCategoriaPediatrico()
		}

		render request.JSON
	}
	
	/**
	 * Listo todos los síntomas del paciente.
	 * @return
	 */
	def getSintomas(){
		Paciente paciente = Paciente.get(request.JSON.id)
		List sintomas = new ArrayList()
		for (s in paciente.sintomas) {
			sintomas.add(s)
		}
		render sintomas as JSON
	}

	/**
	 * Este método sirve para enviar por JSON
	 * los signos vitales ya cargados del paciente
	 * @return
	 */
	def getSignosVitales(){
		Paciente paciente = Paciente.get(request.JSON.id)
		if (paciente.sistole != null) request.JSON.sistole = paciente.sistole
		if (paciente.diastole != null) request.JSON.diastole = paciente.diastole
		if (paciente.temperatura != null) request.JSON.temperatura = paciente.temperatura
		if (paciente.pulso != null) request.JSON.pulso = paciente.pulso
		if (paciente.frecuenciaRespiratoria != null) request.JSON.frecuenciaRespiratoria = paciente.frecuenciaRespiratoria
		if (paciente.glucosa != null) request.JSON.glucosa = paciente.glucosa
		if (paciente.saturacionO2 != null) request.JSON.saturacionO2 = paciente.saturacionO2

		render request.JSON
	}

	@Transactional
	def cargarSintomasYResponder(){
		Paciente paciente = Paciente.get(request.JSON.id)
		this.cargarSintomas(paciente)
		this.enviarRespuesta(paciente)
	}

	def cargarSintomas(Paciente paciente){
		/*request.JSON.sintomas.each {
		 paciente.addToSintomas(Sintoma.get(it.id))
		 }*/
		List resultado = new ArrayList()
		request.JSON.sintomas.each {
			resultado.add(Sintoma.get(it.id))
		}
		paciente.sintomas = resultado //piso los sintomas agregados anteriormente. Con esto evito que se carguen repetidos y
		//cubro la posibilidad de poder borrar sintomas cargados anteriormente

		if(request.JSON.esPrioridadUno){
			paciente.prioridad = Prioridad.UNO
			paciente.save()
		}else{
			paciente.calcularPrioridad()
		}
	}

	def traerDatosPaciente(){
		this.enviarRespuesta(Paciente.get(request.JSON.id))
	}

	/**
	 * 
	 * @param paciente
	 * @return
	 */
	def enviarRespuesta(Paciente paciente){
		request.JSON.nombre = paciente.persona.nombre
		request.JSON.apellido = paciente.persona.apellido
		request.JSON.fechaDeNacimiento = paciente.persona.fechaDeNacimiento.getDateString()
		request.JSON.dni = paciente.persona.dni

grails-app/views/paciente/_form.gsp
Integer tipoFin = request.JSON.tipoFin
		Paciente paciente = Paciente.get(request.JSON.id)
		paciente.tipoAtencion = tipoFin
		paciente.finalizado = true
		paciente.save(flush:true)<%@ page import="triage.Paciente" %>



<div class="fieldcontain ${hasErrors(bean: pacienteInstance, field: 'persona', 'error')} required">
	<label for="persona">
		<g:message code="paciente.persona.label" default="Persona" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="persona" name="persona.id" from="${triage.Persona.list()}" optionKey="id" required="" value="${pacienteInstance?.persona?.id}" class="many-to-one"/>
</div>

grails-app/views/paciente/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'paciente.label', default: 'Paciente')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-paciente" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-paciente" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${pacienteInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${pacienteInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:pacienteInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/paciente/edit.gsp
<%@ page import="triage.Paciente" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'paciente.label', default: 'Paciente')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-paciente" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-paciente" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${pacienteInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${pacienteInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:pacienteInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${pacienteInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/paciente/index.gsp
<%@ page import="triage.Paciente" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'paciente.label', default: 'Paciente')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-paciente" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-paciente" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<th><g:message code="paciente.persona.label" default="Persona" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${pacienteInstanceList}" status="i" var="pacienteInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${pacienteInstance.id}">${fieldValue(bean: pacienteInstance, field: "persona")}</g:link></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${pacienteInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/paciente/show.gsp
<%@ page import="triage.Paciente" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'paciente.label', default: 'Paciente')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-paciente" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-paciente" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list paciente">
			
				<g:if test="${pacienteInstance?.persona}">
				<li class="fieldcontain">
					<span id="persona-label" class="property-label"><g:message code="paciente.persona.label" default="Persona" /></span>
					
						<span class="property-value" aria-labelledby="persona-label"><g:link controller="persona" action="show" id="${pacienteInstance?.persona?.id}">${pacienteInstance?.persona?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:pacienteInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${pacienteInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>