grails-app/domain/triage/Persona.groovy
/* 
Copyright (C) 2015  Nestor Muñoz. nestorgabriel2008@gmail.com; Marcia Tejeda. tejedamarcia@gmail.com

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/

package triage

class Persona { //implements Serializable{

    String dni 
	String nombre
	String apellido
	Date fechaDeNacimiento
	String direccion 
	String telefono 
	String obraSocial 
	String nroAfiliado	

    static hasMany = [pacientes : Paciente]    

    static constraints = {
		apellido blank: false
		nombre blank:false
		dni nullable: true 
		direccion nullable: true
		telefono nullable: true
		obraSocial nullable: true
		nroAfiliado nullable: true 
		fechaDeNacimiento(validator: { val, obj ->
			val < new Date()//validacion para que la fecha de nacimiento no sea futura
		})
    }
	
	//PK = nombre + apellido + fechaDeNacimiento
//	static mapping = {
//		id composite: ['nombre','apellido','fechaDeNacimiento']
//	}

	Boolean esAdulto(){
		return getEdad() > 14 //a partir de los 15 anios una persona es considerada adulta para el triage
	}

	int getEdad(){
		int edad = (new Date() - fechaDeNacimiento) / 365 //la resta de date retorna la cantidad de dias, dividido 365 retorna la cantidad de anios
		return edad
	}

	String getDescripcionEdad(){
		int dias = new Date() - this.fechaDeNacimiento//retorna la diferencia en dias
		if(dias < 30){
			return dias + " dias"
		}else{
			if(dias < 365){
				return ((int) dias / 30) + " meses"
			}else{
				return (int) dias / 365
			}			
		}
	}

	/**
	* Este metodo se utiliza para la logica de los signos vitales y las prioridades en pediatricos
	*/
	String getCategoriaPediatrico(){
		int edad = this.getEdad()
		if(edad > 5){
			return 'mayorDe6Anios'
		}else{
			if(edad > 0 && edad < 6){
				return 'menorDe6Anios'
			}else{
				return 'menorDeUnAnio'
			}
		}
	}

	Boolean esMenorDeTresMeses(){
		int meses = (new Date() - fechaDeNacimiento) / 30
		return meses < 3
	}

	Boolean estaEntre3y36Meses(){
		int meses = (new Date() - fechaDeNacimiento) / 30
		return meses > 2 && meses < 36
	}

	Boolean esMayorDe6Anios(){
		return this.getCategoriaPediatrico() == 'mayorDe6Anios'
	}

	Boolean esMenorDe6Anios(){
		return this.getCategoriaPediatrico() == 'menorDe6Anios'
	}

	Boolean esMenorDeUnAnio(){
		return this.getCategoriaPediatrico() == 'menorDeUnAnio'
	}

}

grails-app/controllers/triage/PersonaController.groovy
/* 
Copyright (C) 2015  Nestor Muñoz. nestorgabriel2008@gmail.com; Marcia Tejeda. tejedamarcia@gmail.com

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/

package triage

import static org.springframework.http.HttpStatus.*

import java.net.Authenticator.RequestorType;

import org.codehaus.groovy.grails.web.binding.bindingsource.JsonDataBindingSourceCreator.JsonArrayList;
import org.codehaus.groovy.grails.web.json.JSONObject;

import grails.converters.JSON
import grails.transaction.Transactional

import java.text.SimpleDateFormat

@Transactional //(readOnly = true) esto me hizo romper la cabeza durante unas cuantas horas :(
class PersonaController extends LoginController{

    static allowedMethods = [ ajaxList: "GET"
								,ajaxSave: "POST"
								,ajaxBuscar: "POST"
								,cargarPersona: "POST"]


	/**
	 * Submit del formulario de alta de persona
	 * @return
	 */
	@Transactional
	def ajaxSave() {
		//validacion para request desde herramientas como curl
		if(request.JSON.nombre == null || request.JSON.apellido == null || request.JSON.fechaDeNacimiento == null){
			return
		}

		SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
		Date fechaDeNacimiento = sdf.parse(request.JSON.fechaDeNacimiento);

		def persona = new Persona(
			nombre : request.JSON.nombre.toUpperCase(),
			apellido : request.JSON.apellido.toUpperCase(),
			fechaDeNacimiento : fechaDeNacimiento,
			dni : request.JSON.dni,
			direccion : request.JSON.direccion,
			telefono : request.JSON.telefono,
			obraSocial : request.JSON.obraSocial,
			nroAfiliado : request.JSON.nroAfiliado
		).save( failOnError : true, flush:true )
		
		Paciente paciente = new Paciente(persona: persona,fechaHoraIngreso: new Date()).save( failOnError : true )
		
		
		request.JSON.id = paciente.id
		request.JSON.nombre = persona.nombre
		request.JSON.apellido = persona.apellido
		request.JSON.fechaDeNacimiento = persona.fechaDeNacimiento.getDateString()
		request.JSON.DNI = persona.dni
		Boolean esAdulto = persona.esAdulto()
		request.JSON.esAdulto = esAdulto
		if(!esAdulto){//es pediatrico
			request.JSON.categoriaPediatrico = persona.getCategoriaPediatrico()
		}
		 
		render request.JSON //retorna el id del paciente + los datos de la persona
	}
	
	def ajaxList() {
		render Persona.findAll( "from Persona p" ) as JSON
	}
	
	/**submit del formulario del listado de busqueda de pacientes
	 *  
	 */
	def ajaxBuscar() {		
	//CON CRITERIA				
		List resultado = Persona.withCriteria {
			if (request.JSON.dni != '' && request.JSON.dni != null){
				ilike("dni",request.JSON.dni+"%") //ilike es un like case insensitive 
			}
			if (request.JSON.apellido != '' && request.JSON.apellido != null){
				ilike("apellido",request.JSON.apellido+"%")
			}
			if (request.JSON.nombre != '' && request.JSON.nombre != null){
				ilike("nombre",request.JSON.nombre+"%")
			}
			if (request.JSON.fechaDeNacimiento  != '' && request.JSON.fechaDeNacimiento  != null){
				SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
				Date fechaDeNacimiento = dateFormat.parse(request.JSON.fechaDeNacimiento);
				eq("fechaDeNacimiento",fechaDeNacimiento)
			}
		}		
		render resultado as JSON		
		return resultado	
	}	
	
	def cargarPersona(){
		Persona persona = Persona.get(request.JSON.id)
		request.JSON.nombre = persona.nombre
		request.JSON.apellido = persona.apellido
		request.JSON.fechaDeNacimiento = persona.fechaDeNacimiento.getDateString()
		request.JSON.dni = persona.dni
		request.JSON.direccion = persona.direccion
		request.JSON.telefono = persona.telefono
		request.JSON.obraSocial = persona.obraSocial
		request.JSON.nroAfiliado = persona.nroAfiliado
		
		String sql = "SELECT p.prioridad, p.id, p.fechaHoraAtencion, p.diastole, p.sistole, p.temperatura, "+
						"p.frecuenciaRespiratoria, p.glucosa, p.pulso, p.saturacionO2,"+
						" p.tipoAtencion FROM Paciente p where  finalizado = TRUE and persona_id = "+persona.id
						
		List consultaAtenciones = Paciente.executeQuery(sql)
		List atencionesResp = new ArrayList()
		for (atencion in consultaAtenciones) {
			String prioridad = traerPrioridad(atencion[0]);
			String fecha = new SimpleDateFormat("dd-MM-yyyy").format(atencion[2]);
			String sintomas = traerSintomas(atencion[1])
			String tipoAtencion = traerTipoAtencion(atencion[10])
			String presion = traerPresion(atencion[3], atencion[4])
			atencionesResp.add(new JSONObject('{"id":' + atencion[1] +
				',"prioridad":"' + prioridad + '"' +
				',"fechaAtencion":' + fecha +
				',"presion":' + presion +
				',"temperatura":' + atencion[5] +
				',"frecuencia":' + atencion[6] +
				',"glucosa":' + atencion[7] +
				',"pulso":' + atencion[8] +
				',"saturacion":' + atencion[9] +
				',"sintomas":' + sintomas +
				',"tipoAtencion":"' + tipoAtencion+ '"}'))
		}
		
		//println atencionesResp
		
		request.JSON.atenciones = atencionesResp
		render request.JSON as JSON
	}
	
	def traerTipoAtencion(Long nta){
		switch(nta){
			 case 1:
			 	return "Ingresa"
			 case 2:
			 	return "Consultorio externo"
			 case 3:
			 	return "Retira sin atención"
		}
			
	}
	
	def traerPresion(p1, p2){
		if (p1 == null || p2 == null) return null
		else return p1+"-"+p2
		
	}
	
	def traerSintomas (Long nid){
		Paciente p = Paciente.get(nid)
		List sintomas = new ArrayList()
		String ss = ""
		for (s in p.sintomas) {
			sintomas.add(s.nombre)
			ss = ss+" - "+(s.nombre)
		}
		if (ss == "") return null
		else return ss
	}
	
	String traerPrioridad (Prioridad p){
		if (p == Prioridad.UNO) return "Prioridad UNO"
		if (p == Prioridad.DOS) return "Prioridad DOS"
		if (p == Prioridad.TRES) return "Prioridad TRES"
		if (p == null) return "No se ha calculado"
	}
	
			
}

grails-app/views/persona/_form.gsp
<%@ page import="triage.Persona" %>



<div class="fieldcontain ${hasErrors(bean: personaInstance, field: 'apellido', 'error')} required">
	<label for="apellido">
		<g:message code="persona.apellido.label" default="Apellido" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="apellido" required="" value="${personaInstance?.apellido}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: personaInstance, field: 'direccion', 'error')} ">
	<label for="direccion">
		<g:message code="persona.direccion.label" default="Direccion" />
		
	</label>
	<g:textField name="direccion" value="${personaInstance?.direccion}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: personaInstance, field: 'dni', 'error')} required">
	<label for="dni">
		<g:message code="persona.dni.label" default="Dni" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="dni" type="number" value="${personaInstance.dni}" required=""/>
</div>

<div class="fieldcontain ${hasErrors(bean: personaInstance, field: 'fechaDeNacimiento', 'error')} ">
	<label for="fechaDeNacimiento">
		<g:message code="persona.fechaDeNacimiento.label" default="Fecha De Nacimiento" />
		
	</label>
	<g:textField name="fechaDeNacimiento" value="${personaInstance?.fechaDeNacimiento}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: personaInstance, field: 'nombre', 'error')} ">
	<label for="nombre">
		<g:message code="persona.nombre.label" default="Nombre" />
		
	</label>
	<g:textField name="nombre" value="${personaInstance?.nombre}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: personaInstance, field: 'nroAfiliado', 'error')} required">
	<label for="nroAfiliado">
		<g:message code="persona.nroAfiliado.label" default="Nro Afiliado" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="nroAfiliado" type="number" value="${personaInstance.nroAfiliado}" required=""/>
</div>

<div class="fieldcontain ${hasErrors(bean: personaInstance, field: 'obraSocial', 'error')} ">
	<label for="obraSocial">
		<g:message code="persona.obraSocial.label" default="Obra Social" />
		
	</label>
	<g:textField name="obraSocial" value="${personaInstance?.obraSocial}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: personaInstance, field: 'pacientes', 'error')} ">
	<label for="pacientes">
		<g:message code="persona.pacientes.label" default="Pacientes" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${personaInstance?.pacientes?}" var="p">
    <li><g:link controller="paciente" action="show" id="${p.id}">${p?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="paciente" action="create" params="['persona.id': personaInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'paciente.label', default: 'Paciente')])}</g:link>
</li>
</ul>

</div>

<div class="fieldcontain ${hasErrors(bean: personaInstance, field: 'telefono', 'error')} required">
	<label for="telefono">
		<g:message code="persona.telefono.label" default="Telefono" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="telefono" type="number" value="${personaInstance.telefono}" required=""/>
</div>

grails-app/views/persona/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'persona.label', default: 'Persona')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-persona" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-persona" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${personaInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${personaInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:personaInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/persona/edit.gsp
<%@ page import="triage.Persona" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'persona.label', default: 'Persona')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-persona" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-persona" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${personaInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${personaInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:personaInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${personaInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/persona/index.gsp
<%@ page import="triage.Persona" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'persona.label', default: 'Persona')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-persona" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-persona" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="dni" title="${message(code: 'persona.dni.label', default: 'Dni')}" />
					
						<g:sortableColumn property="apellido" title="${message(code: 'persona.apellido.label', default: 'Apellido')}" />
					
						<g:sortableColumn property="direccion" title="${message(code: 'persona.direccion.label', default: 'Direccion')}" />
					
						<g:sortableColumn property="fechaDeNacimiento" title="${message(code: 'persona.fechaDeNacimiento.label', default: 'Fecha De Nacimiento')}" />
					
						<g:sortableColumn property="nombre" title="${message(code: 'persona.nombre.label', default: 'Nombre')}" />
					
						<g:sortableColumn property="nroAfiliado" title="${message(code: 'persona.nroAfiliado.label', default: 'Nro Afiliado')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${personaInstanceList}" status="i" var="personaInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${personaInstance.id}">${fieldValue(bean: personaInstance, field: "dni")}</g:link></td>
					
						<td>${fieldValue(bean: personaInstance, field: "apellido")}</td>
					
						<td>${fieldValue(bean: personaInstance, field: "direccion")}</td>
					
						<td>${fieldValue(bean: personaInstance, field: "fechaDeNacimiento")}</td>
					
						<td>${fieldValue(bean: personaInstance, field: "nombre")}</td>
					
						<td>${fieldValue(bean: personaInstance, field: "nroAfiliado")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${personaInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/persona/show.gsp
<%@ page import="triage.Persona" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'persona.label', default: 'Persona')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-persona" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-persona" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list persona">
			
				<g:if test="${personaInstance?.apellido}">
				<li class="fieldcontain">
					<span id="apellido-label" class="property-label"><g:message code="persona.apellido.label" default="Apellido" /></span>
					
						<span class="property-value" aria-labelledby="apellido-label"><g:fieldValue bean="${personaInstance}" field="apellido"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${personaInstance?.direccion}">
				<li class="fieldcontain">
					<span id="direccion-label" class="property-label"><g:message code="persona.direccion.label" default="Direccion" /></span>
					
						<span class="property-value" aria-labelledby="direccion-label"><g:fieldValue bean="${personaInstance}" field="direccion"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${personaInstance?.dni}">
				<li class="fieldcontain">
					<span id="dni-label" class="property-label"><g:message code="persona.dni.label" default="Dni" /></span>
					
						<span class="property-value" aria-labelledby="dni-label"><g:fieldValue bean="${personaInstance}" field="dni"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${personaInstance?.fechaDeNacimiento}">
				<li class="fieldcontain">
					<span id="fechaDeNacimiento-label" class="property-label"><g:message code="persona.fechaDeNacimiento.label" default="Fecha De Nacimiento" /></span>
					
						<span class="property-value" aria-labelledby="fechaDeNacimiento-label"><g:fieldValue bean="${personaInstance}" field="fechaDeNacimiento"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${personaInstance?.nombre}">
				<li class="fieldcontain">
					<span id="nombre-label" class="property-label"><g:message code="persona.nombre.label" default="Nombre" /></span>
					
						<span class="property-value" aria-labelledby="nombre-label"><g:fieldValue bean="${personaInstance}" field="nombre"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${personaInstance?.nroAfiliado}">
				<li class="fieldcontain">
					<span id="nroAfiliado-label" class="property-label"><g:message code="persona.nroAfiliado.label" default="Nro Afiliado" /></span>
					
						<span class="property-value" aria-labelledby="nroAfiliado-label"><g:fieldValue bean="${personaInstance}" field="nroAfiliado"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${personaInstance?.obraSocial}">
				<li class="fieldcontain">
					<span id="obraSocial-label" class="property-label"><g:message code="persona.obraSocial.label" default="Obra Social" /></span>
					
						<span class="property-value" aria-labelledby="obraSocial-label"><g:fieldValue bean="${personaInstance}" field="obraSocial"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${personaInstance?.pacientes}">
				<li class="fieldcontain">
					<span id="pacientes-label" class="property-label"><g:message code="persona.pacientes.label" default="Pacientes" /></span>
					
						<g:each in="${personaInstance.pacientes}" var="p">
						<span class="property-value" aria-labelledby="pacientes-label"><g:link controller="paciente" action="show" id="${p.id}">${p?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${personaInstance?.telefono}">
				<li class="fieldcontain">
					<span id="telefono-label" class="property-label"><g:message code="persona.telefono.label" default="Telefono" /></span>
					
						<span class="property-value" aria-labelledby="telefono-label"><g:fieldValue bean="${personaInstance}" field="telefono"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:personaInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${personaInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>